# Generated by Django 4.2.2 on 2026-09-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("started_on_page", models.CharField(blank=True, max_length=200)),
                ("user_message_count", models.PositiveIntegerField(default=0)),
                ("questions_flagged", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat transcript",
                "verbose_name_plural": "Chat transcripts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="Write it the way a client would ask it.",
                        max_length=300,
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Write it the way you'd answer a client. The assistant only knows what's written in these FAQs, so include real prices, policies and details."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide this from the assistant without deleting it.",
                        verbose_name="Assistant uses this",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower numbers are listed first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs (what the assistant knows)",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UnansweredQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                (
                    "normalized",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=500
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True,
                        help_text="Type the answer the way you'd tell a client, then Save. It's added to the FAQs automatically and the assistant starts using it right away.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Needs an answer"),
                            ("answered", "Answered (added to FAQs)"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("times_asked", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_asked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The chat where this was most recently asked.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unanswered_questions",
                        to="chatbot.conversation",
                    ),
                ),
                (
                    "faq",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_question",
                        to="chatbot.faq",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question to answer",
                "verbose_name_plural": "Questions to answer",
                "ordering": ["-last_asked_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Visitor"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("is_fallback", models.BooleanField(default=False)),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveIntegerField(default=0)),
                ("cache_write_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["role", "created_at"],
                        name="chatbot_mes_role_77257c_idx",
                    ),
                    models.Index(
                        fields=["ip_hash", "created_at"],
                        name="chatbot_mes_ip_hash_f50adf_idx",
                    ),
                ],
            },
        ),
    ]
