# Generated by Django 4.2.2 on 2026-01-29 01:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetPortraitSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_photo', models.ImageField(upload_to='pet_submissions/')),
                ('additional_notes', models.TextField(blank=True, help_text='Any special requests or details about the pet')),
                ('portrait_size', models.CharField(choices=[('8x10', '8" x 10" - $150'), ('11x14', '11" x 14" - $200'), ('16x20', '16" x 20" - $300')], default='8x10', max_length=50)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='submitted', max_length=20)),
            ],
            options={
                'verbose_name': 'Pet Portrait Submission',
                'verbose_name_plural': 'Pet Portrait Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
