# Generated by Django 4.2.2 on 2026-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petportraitsubmission',
            name='portrait_size',
            field=models.CharField(choices=[('5x7', '5" x 7" - $50'), ('8x10', '8" x 10" - $85'), ('11x14', '11" x 14" - $160'), ('16x20', '16" x 20" - $320')], default='8x10', max_length=50),
        ),
    ]
