# Generated by Django 4.2.2 on 2023-10-05 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePaintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Client Name')),
                ('phone', models.CharField(max_length=60, verbose_name='Phone')),
                ('event_date', models.DateField(verbose_name='Event Date')),
                ('venue', models.CharField(max_length=128, verbose_name='Venue Location')),
                ('guest_count', models.CharField(max_length=128, verbose_name='Estimated Guest Count')),
                ('reference', models.CharField(max_length=128, verbose_name='How Did You Hear About Us?')),
                ('wedding_planner', models.CharField(max_length=128, verbose_name='Event Planner Name')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=256, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='MyClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=60, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=256, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
