# Generated by Django 4.2.6 on 2024-02-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepaintevent',
            name='source',
            field=models.TextField(blank=True, max_length=555),
        ),
    ]
