# Generated by Django 4.2.6 on 2024-05-29 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_livepaintevent_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepaintevent',
            name='instagram',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='ig'),
            preserve_default=False,
        ),
    ]
