# Generated by Django 4.2.2 on 2024-09-08 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_livepaintevent_typeofclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepaintevent',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
