# Generated by Django 4.2.2 on 2025-03-20 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_livepaintevent_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='livepaintevent',
            name='venue_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Venue Name'),
            preserve_default=False,
        ),
    ]
