"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import mimetypes
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.fd
BASE_DIR = Path(__file__).resolve().parent.parent

mimetypes.add_type("text/javascript", ".js", True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-&psk#na5l=p3q8_a+-$4w1f^lt3lx1c@d*p4x$ymm_rn7pwb87')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False #os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'paintedbykarla.com', 'www.paintedbykarla.com', '.railway.app']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'corsheaders',
    'django.contrib.sitemaps',
    'pages',
    'accounts',
    'reviews',
    'shop',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# Railway provides DATABASE_URL as an environment variable. Never hard-code the
# database password here: this repository is public on GitHub.
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    print("Postgres URL not found, using sqlite instead")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_TRUSTED_ORIGINS = ['https://www.paintedbykarla.com', 'https://paintedbykarla.com']

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Los_Angeles'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images) - FIXED
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise configuration for production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Don't compress videos
WHITENOISE_SKIP_COMPRESS_EXTENSIONS = ('jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'gz', 'tgz', 'mp4', 'webm', 'mov')
WHITENOISE_MIMETYPES = {
    '.mp4': 'video/mp4',
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = "home"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')

# Email alerts for Karla (see mysite/notifications.py).
# Railway blocks SMTP, so alerts go through Resend's HTTPS API when RESEND_API_KEY is set.
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
NOTIFY_TO_EMAIL = os.environ.get('NOTIFY_TO_EMAIL', 'WatercolorsByKarla@hotmail.com')
# onboarding@resend.dev only delivers to the email address on your Resend account.
# Once paintedbykarla.com is verified in Resend, set this to e.g.
# "Watercolors By Karla <hello@paintedbykarla.com>".
NOTIFY_FROM_EMAIL = os.environ.get('NOTIFY_FROM_EMAIL', 'Watercolors By Karla <onboarding@resend.dev>')
SITE_URL = os.environ.get('SITE_URL', 'https://www.paintedbykarla.com')

# Website assistant (chatbot app). It stays hidden until ANTHROPIC_API_KEY is set.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
# Kill switch: set CHATBOT_ENABLED=false in Railway to hide the chat without a code change.
CHATBOT_ENABLED = (
    os.environ.get('CHATBOT_ENABLED', 'true').lower() not in ('false', '0', 'no', 'off')
    and bool(ANTHROPIC_API_KEY)
)
CHATBOT_MODEL = os.environ.get('CHATBOT_MODEL', 'claude-sonnet-5')
CHATBOT_EFFORT = os.environ.get('CHATBOT_EFFORT', 'low')
CHATBOT_DAILY_MESSAGE_LIMIT = int(os.environ.get('CHATBOT_DAILY_MESSAGE_LIMIT', '600'))
CHATBOT_CONTACT_EMAIL = 'WatercolorsbyKarla@gmail.com'

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'mysite.log',
            'formatter': 'verbose'
        },
        # Shows up in Railway's deploy logs.
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'MYAPP': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'chatbot': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'mysite.notifications': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    }
}

# Stripe Configuration (add at the bottom)
# Stripe Configuration (TEMPORARY - for development only)
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = ''  # We'll add this later