# Generated by Django 4.2.2 on 2024-08-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
