# Generated by Django 6.0.1 on 2026-01-26 19:39
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_auto_20260124_1704'),  # This matches what's in production
    ]
    
    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]